# These done 2/15/2025
# brew install pre-commit
# pre-commit install
# pre-commit run

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

#  - repo: https://github.com/psf/black-pre-commit-mirror
# I didn't like how this split lines with long strings of dictionary keys
#    rev: "25.1.0"
#    hooks:
#      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.7"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: "v1.15.0"
#    hooks:
#      - id: mypy
#        files: src|tests
#        args: ["--disable-error-code=import-untyped", "--disable-error-code=import-not-found"]
